pipeline {
    agent any
    environment {
        APP_NAME = 'medusa-app'
    }
    stages {
        stage('Checkout Latest Code') {
            steps {
                git branch: 'main', url: 'https://github.com/vetryselvan1307-design/medusa.git'
            }
        }

        stage('Stop Old Containers') {
            steps {
                dir('my-medusa-store') {
                    sh 'docker-compose down || true'
                }
            }
        }

        stage('Build New Images') {
            steps {
                dir('my-medusa-store') {
                    sh 'docker-compose build'
                }
            }
        }

        stage('Deploy New Version') {
            steps {
                dir('my-medusa-store') {
                    sh 'docker-compose up -d'
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
