pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/vetryselvan1307-design/medusa.git'
    }

    stages {
        stage('Checkout Code') {
            steps {
                // Checkout latest code from main branch
                git branch: 'main', url: "${REPO_URL}"
            }
        }

        stage('Stop Old Containers') {
            steps {
                // Stop and remove existing containers (if any)
                sh 'docker-compose down'
            }
        }

        stage('Build New Images') {
            steps {
                // Build all Docker images defined in docker-compose.yml
                sh 'docker-compose build'
            }
        }

        stage('Deploy New Version') {
            steps {
                // Run containers in detached mode
                sh 'docker-compose up -d'
            }
        }
    }

    post {
        success {
            echo 'Deployment successful!'
        }
        failure {
            echo 'Deployment failed!'
        }
    }
}
