pipeline {
    agent any

    environment {
        REPO_URL = 'https://github.com/vetryselvan1307-design/medusa.git'
        APP_NAME = 'medusa-app'
        PORT = '9000'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "${REPO_URL}"
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('my-medusa-store') {
                    sh "docker build -t ${APP_NAME} ."
                }
            }
        }

        stage('Stop Existing Container') {
            steps {
                dir('my-medusa-store') {
                    sh """
                    docker stop ${APP_NAME} || true
                    docker rm ${APP_NAME} || true
                    """
                }
            }
        }

        stage('Run Docker Container') {
            steps {
                dir('my-medusa-store') {
                    sh "docker run -d -p ${PORT}:9000 --name ${APP_NAME} ${APP_NAME}"
                }
            }
        }
    }

    post {
        success {
            echo "Deployment successful!"
        }
        failure {
            echo "Deployment failed!"
        }
    }
}
